<?php

namespace Type;

require_once dirname(__FILE__) . '/../../../app/Type/Number.php';

/**
 * Test class for Number.
 * Generated by PHPUnit on 2011-07-24 at 18:00:17.
 */
class NumberTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Number
     */
    protected $object;

    protected function setUp() {
        $this->object = new Number(5);
    }

    public function testConstructorWithInteger() {
        $number = new Number(5);
        $this->assertEquals(5, $number->getNativeValue());
    }

    public function testConstructorWithAnotherNumber() {
        $this->assertEquals(new Number(5), new Number($this->object));
    }




    public function testAdd() {
        $this->assertEquals(new Number(9), $this->object->add(4));
    }

    public function testSubtract() {
        $this->assertEquals(new Number(1), $this->object->subtract(4));
    }

    public function testMultiply() {
        $this->assertEquals(new Number(10), $this->object->multiply(2));
    }

    public function testDivide() {
        $this->assertEquals(new Number(2.5), $this->object->divide(2));
    }

    /**
     * @expectedException InvalidArgumentException
     */
    public function testDivideByZeroThrowsInvalidArgumentException() {
        $this->object->divide(0);
    }


    public function testToString() {
        $this->assertEquals(new String('5'), $this->object->toString());
    }


    /**
     * @expectedException InvalidArgumentException
     */
    public function testToStringWithABaseOtherThanTenThrowsInvalidArgumentException() {
        $this->object->toString(12);
    }


    /**
     * @expectedException \Exception
     */
    public function testToExponential() {
        $this->object->toExponential();
    }

    /**
     * @expectedException \Exception
     */
    public function testToFixed() {
        $this->object->toFixed();
    }

    /**
     * @expectedException \Exception
     */
    public function testToPrecision() {
        $this->object->toPrecision();

    }

    /**
     * @expectedException \Exception
     */
    public function testToLocaleString() {
        $this->object->toLocaleString();
    }

}

?>
