#                                                                        #
# Security policy definition                                             #
#                                                                        #
# Settings for the Events package                                        #
