<?php

namespace ToDate\Iterator;

use ToDate\Condition;

require_once TODATE_BASEDIR . '/ToDate/Iterator/ConditionIterator.php';


/**
 * Test class for ConditionIterator.
 * Generated by PHPUnit on 2012-02-08 at 20:52:54.
 */
class ConditionIteratorTest extends \PHPUnit_Framework_TestCase {


	/**
	 * @covers ToDate\Iterator\ConditionIterator::__construct
	 * @covers ToDate\Iterator\ConditionIterator::accept
	 */
	public function testAcceptNothingWithNeverCondition() {
		$it = new ConditionIterator(new DayIterator('2012-01-01','2012-01-02'), new Condition\NeverCondition());
		self::assertFalse($it->accept());
		
		$results = array();
		foreach ($it as $date) {
			$results[] = $date;
		}
		self::assertCount(0, $results);

		
	}
	
	/**
	 * @covers ToDate\Iterator\ConditionIterator::__construct
	 * @covers ToDate\Iterator\ConditionIterator::accept
	 */
	public function testAcceptAllWithAlwaysCondition() {
		$it = new ConditionIterator(new DayIterator('2012-01-01','2012-01-02'), new Condition\AlwaysCondition());
		self::assertTrue($it->accept());
		
		$results = array();
		foreach ($it as $date) {
			$results[] = $date;
		}
		self::assertCount(2, $results);

	}
	

}

?>
