#                                                                        #
# Security policy definition                                             #
#                                                                        #
# Settings for the Events package                                        #

TYPO3:
  Flow:
    security:
      authentication:
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: 'account/login'

Org:
  Gucken:
    Events:
      midnightHour: 5
      currentView: default
      views:
        default:
          layoutRootPath: resource://Org.Gucken.Events/Private/Layouts
          templateRootPath: resource://Org.Gucken.Events/Private/Templates
          partialRootPath: resource://Org.Gucken.Events/Private/Partials
          partialRootPath: resource://Org.Gucken.Events/Private/Partials
          skinPackage: Org.Gucken.Events