#                                                                        #
# Security policy definition                                             #
#                                                                        #
# Settings for the Events package                                        #
TYPO3:
  FLOW3:
    security:
      authentication:
        providers:
          DefaultProvider:
            providerClass: PersistedUsernamePasswordProvider
            entryPoint:
              WebRedirect:
                uri: org.gucken.events/account/index
              
Org:
  Gucken:
    Events:
      view: default
      views:         
        default:
          layoutRootPath: resource://Org.Gucken.Events/Private/Layouts
          templateRootPath: resource://Org.Gucken.Events/Private/Templates
          partialRootPath: resource://Org.Gucken.Events/Private/Partials
        bielefeld:
          layoutRootPath: resource://Org.Gucken.Bielefeld/Private/Layouts
          templateRootPath: resource://Org.Gucken.Bielefeld/Private/Templates
          partialRootPath: resource://Org.Gucken.Bielefeld/Private/Partials
          