#                                                                        #
# Security policy definition                                             #
#                                                                        #
# Settings for the Events package                                        #

TYPO3:
  FLOW3:
    security:
      authentication:
        providers:
          DefaultProvider:
            providerClass: PersistedUsernamePasswordProvider
            entryPoint:
              WebRedirect:
                uri: account/login

Org:
  Gucken:
    Events:
      midnightHour: 5
      currentView: default
      views:
        default:
          layoutRootPath: resource://Org.Gucken.Events/Private/Layouts
          templateRootPath: resource://Org.Gucken.Events/Private/Templates
          partialRootPath: resource://Org.Gucken.Events/Private/Partials
          partialRootPath: resource://Org.Gucken.Events/Private/Partials
          skinPackage: Org.Gucken.Events