<?php
namespace Tests\Util;

require_once dirname(__FILE__).'/../../../app/Util/String.php';

/**
 * Test class for String.
 * Generated by PHPUnit on 2011-06-14 at 00:21:12.
 */
class StringTest extends \PHPUnit_Framework_TestCase {

    public function testCamelCaseToSeparated() {
        $this->assertEquals(
                'i_am_camel_cased',
                \Util\String::camelCaseToSeparated('iAmCamelCased')
        );

    }

    public function testSeparatedToCamelCase() {
        $this->assertEquals(
                'iAmCamelCased',
                \Util\String::separatedToCamelCase('i_am_camel_cased')
        );
    }

    public function testCamelCaseToNamespace() {
        $this->assertEquals(
                'Type\String\Collection',
                \Util\String::camelCaseToNamespace('TypeStringCollection')
        );
    }

    public function testExpandRangesSimple() {
        $this->assertEquals(
                '1 2 3 4 5',
                \Util\String::expandRangesSimple('1-5', '_from-_to')
        );
    }

    public function testExpandRangesSimpleWithSeparator() {
        $this->assertEquals(
                '1,2,3,4,5',
                \Util\String::expandRangesSimple('1-5', '_from-_to','_item', ',')
        );
    }

    public function testExpandRangesSimpleWithStartAndEndMarkers() {
        $this->assertEquals(
                '{1},{2},{3},{4},{5}',
                \Util\String::expandRangesSimple('1-5', '_from-_to','_item', ',', '{', '}')
        );
    }

    public function testExpandRangesSimpleMultiplieOccurences() {
        $this->assertEquals(
                '{1},{2},{3},{4},{5}|{12},{13},{14}',
                \Util\String::expandRangesSimple('1-5|12-14', '_from-_to', '_item', ',', '{', '}')
        );
    }

    public function testExpandRanges() {
        $this->assertEquals(
                'vom 1. 12. 2. 12. 3. 12. und vom 13. 1. 14. 1. 15. 1. 2011',
                \Util\String::expandRanges(
                        'vom 1. 12. - 3. 12. und vom 13. 1. - 15. 1. 2011',
                        '#(?<from>\d+)\. (\d+)\. - (?<to>\d+)\. (\d+)\.#',
                        '_item. _2.'
                )
        );
    }


    public function testExpandRangesWithSeparatorAndMarkers() {
        $this->assertEquals(
                'vom {1. 12.},{2. 12.},{3. 12.} und vom {13. 1.},{14. 1.},{15. 1.} 2011',
                \Util\String::expandRanges(
                        'vom 1. 12. - 3. 12. und vom 13. 1. - 15. 1. 2011',
                        '#(?<from>\d+)\. (\d+)\. - (?<to>\d+)\. (\d+)\.#',
                        '_item. _2.',
                        ',' ,
                        '{',
                        '}'
                )
        );
    }




}
?>
