#                                                                        #
# Security policy definition                                             #
#                                                                        #
# Settings for the Events package                                        #
Org:
  Gucken:
    Events:
      this: dev